name: Deploy to AWS S3

on:
  push:
    branches:
      - master  # Deploys only when pushing to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm install

      - name: Run 11ty Build
        run: npx @11ty/eleventy --input ./portfolio --output ./portfolio/_site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: aws s3 sync ./portfolio s3://${{ secrets.S3_BUCKET_NAME }} --delete --acl public-read

      - name: Invalidate CloudFront Dist 1
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUD_FRONT_DIST_ID_1 }} \
            --paths "/*"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        if: ${{ success() }}

      - name: Invalidate CloudFront Dist 2
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUD_FRONT_DIST_ID_2 }} \
            --paths "/*"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        if: ${{ success() }}
